### ISSUE TITLE
Internal splitting of data leads to mismatch between `test_size` and number of `classes` for multiclass problem

### ISSUE THREAD

**Issue by navdeep-G** [interpretml/interpret#142]
* First of all, thank you so much for this package. It is great!
* For the issue at hand, I am trying to run `EBM` with a multiclass outcome and received the following error:

```
import numpy as np
import pandas as pd
from interpret.glassbox import (
    ExplainableBoostingClassifier,
    ExplainableBoostingRegressor,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('weather_secret.csv')
df.dropna(axis=0, inplace=True)
df = df.groupby("secret_Pressure9am").filter(lambda x: len(x) > 4) # Need to do this to ensure number of counts
                                                                   # per class is enough
df.shape

print(f"Unique values for target, 'secret_Pressure9am:\n', {df['secret_Pressure9am'].value_counts()}")

train_cols = list(df.columns)
train_cols.remove("secret_Pressure9am")

X = df[train_cols]

labels = list(np.unique(df.secret_Pressure9am.values))
lb = LabelEncoder()
lb.fit(labels)
y = lb.transform(df.secret_Pressure9am)

seed = 1
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=seed)

print("\n")
ebm = ExplainableBoostingClassifier(random_state=seed)
ebm.fit(X_train, y_train)
```
which leads to 

```
2020-06-09 16:44:34,438 C:▁ D:2.3TB M:213.7GB 4095  WARNING: Passing a numpy array to schema autogen when it should be dataframe.
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 600, in __call__
    return self.func(*args, **kwargs)
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/interpret/glassbox/ebm/ebm.py", line 854, in train_model
    return estimator.fit_parallel(X, y, n_classes)
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/interpret/glassbox/ebm/ebm.py", line 409, in fit_parallel
    is_classification=self.model_type == "classification",
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/interpret/glassbox/ebm/utils.py", line 39, in ebm_train_test_split
    stratify=y if is_classification else None,
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 2121, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 1323, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/home/navdeep/h2oai/env_dev/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 1648, in _iter_indices
    (n_test, n_classes))
ValueError: The test_size = 3 should be greater or equal to the number of classes = 4
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-326-7a53ea44f9a2> in <module>
     23 print("\n")
     24 ebm = ExplainableBoostingClassifier(random_state=seed)
---> 25 ebm.fit(X_train, y_train)

~/h2oai/env_dev/lib/python3.6/site-packages/interpret/glassbox/ebm/ebm.py in fit(self, X, y)
    858         )
    859 
--> 860         estimators = provider.parallel(train_model, train_model_args_iter)
    861 
    862         if isinstance(self.interactions, int) and self.interactions > 0:

~/h2oai/env_dev/lib/python3.6/site-packages/interpret/provider/compute.py in parallel(self, compute_fn, compute_args_iter)
     19     def parallel(self, compute_fn, compute_args_iter):
     20         results = Parallel(n_jobs=self.n_jobs)(
---> 21             delayed(compute_fn)(*args) for args in compute_args_iter
     22         )
     23         # NOTE: Force gc, as Python does not free native memory easy.

~/h2oai/env_dev/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
   1014 
   1015             with self._backend.retrieval_context():
-> 1016                 self.retrieve()
   1017             # Make sure that we get a last message telling us we are done
   1018             elapsed_time = time.time() - self._start_time

~/h2oai/env_dev/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    906             try:
    907                 if getattr(self._backend, 'supports_timeout', False):
--> 908                     self._output.extend(job.get(timeout=self.timeout))
    909                 else:
    910                     self._output.extend(job.get())

~/h2oai/env_dev/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    552         AsyncResults.get from multiprocessing."""
    553         try:
--> 554             return future.result(timeout=timeout)
    555         except LokyTimeoutError:
    556             raise TimeoutError()

/usr/local/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

/usr/local/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: The test_size = 3 should be greater or equal to the number of classes = 4
```

* The dataset to repro is [attached](https://github.com/interpretml/interpret/files/4755437/weather_secret.csv.zip) and the version of `interpret` I used is `0.1.20`.
* Please let me know if more information is needed. Thanks!

**Comment by interpret-ml** [comment]
Hi @navdeep-G, 

Thanks for reporting this in such detail, and our apologies for the delay in getting back to you. Among quite a few large changes, we addressed this issue in our latest v0.2.0 release (see the changelog here: https://github.com/interpretml/interpret/blob/master/CHANGELOG.md#breaking-changes). 

The bug arises when there are too few samples to have at least 1 example of each class in our internal validation set. By default, we set our validation set size to a stratified sample of 15% of the training data, and in cases like yours, this wasn't sufficient to guarantee an example per class. We've introduced a new warning and breaking change that now adapts the validation set size, and continues training without throwing an error. 

Please give our latest update a try, and feel free to re-open if there are any issues!

-InterpretML Team
