### ISSUE TITLE
Segmentation fault in interpret == 0.4.0 

### ISSUE THREAD

**Issue by DaKlaas** [interpretml/interpret#435]
I tried running this block of code on my (8 core, 32 GB, Ubuntu, Python 3.10) machine:
```
model = ExplainableBoostingRegressor(early_stopping_rounds=100)
model.fit(X_train, y_train )
```
The dataset that was used, was very small and should not have resulted in a memory error.
Running this in 0.3.2 never gave this kind of issue. 
Below you will find the error message:

```
The default value of regex will change from True to False in a future version.
Traceback (most recent call last):
  File "/home/klaas/Desktop/code_pen/RMRM/test_objectives.py", line 127, in <module>
    model.fit(X_train, y_train )
  File "/home/klaas/miniconda3/envs/RMRM/lib/python3.10/site-packages/interpret/glassbox/_ebm/_ebm.py", line 848, in fit
    results = provider.parallel(boost, parallel_args)
  File "/home/klaas/miniconda3/envs/RMRM/lib/python3.10/site-packages/interpret/provider/_compute.py", line 19, in parallel
    results = Parallel(n_jobs=self.n_jobs)(
  File "/home/klaas/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/klaas/.local/lib/python3.10/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/klaas/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/klaas/miniconda3/envs/RMRM/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/klaas/miniconda3/envs/RMRM/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGSEGV(-11), SIGSEGV(-11), SIGSEGV(-11)}


```

**Comment by DaKlaas** [comment]
Seems to be a conda issue. Rerunning it in a different environment solved the issue

**Comment by paulbkoch** [comment]
Hi @DaKlaas -- If you still have access to the environment where it is failing, it would be good to get a log to determine where it is crashing.  That can be done by inserting the following at the top of the script before any other calls to interpret:

```
from interpret.develop import debug_mode
debug_mode(log_filename='log.txt', log_level='INFO', native_debug=False)
```
