### ISSUE TITLE
Installation Error with respect to SALib and pyscaffold

### ISSUE THREAD

**Issue by mohitsahay** [interpretml/interpret#73]
Hi,

I am trying to install Interpret with interpret-0.1.17-py3-none-any.whl in an offline environment.

Pls note: It appears similar to [https://github.com/microsoft/interpret/issues/58](url) just in an offline environment..

As there is dependency for SALib>=1.3.3, when I install SALib-1.3.3 getting below error (with PyScaffold version 3.0a2) - 

Traceback (most recent call last):
  File "/home/idap_user/Anaconda3/lib/python3.6/site-packages/pyscaffold/utils.py", line 284, in check_setuptools_version
    from pkg_resources import (  # noqa
ImportError: cannot import name 'SetuptoolsVersion'

During handling of the above exception, another exception occurred:

_Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    setup_package()
  File "setup.py", line 33, in setup_package
    use_pyscaffold=True)
  File "/home/idap_user/Anaconda3/lib/python3.6/site-packages/setuptools-41.2.0-py3.6.egg/setuptools/__init__.py", line 145, in setup
  File "/home/idap_user/Anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/idap_user/Anaconda3/lib/python3.6/site-packages/setuptools-41.2.0-py3.6.egg/setuptools/dist.py", line 446, in __init__
  File "/home/idap_user/Anaconda3/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/home/idap_user/Anaconda3/lib/python3.6/site-packages/setuptools-41.2.0-py3.6.egg/setuptools/dist.py", line 734, in finalize_options
  File "/home/idap_user/Anaconda3/lib/python3.6/site-packages/pyscaffold/integration.py", line 105, in pyscaffold_keyword
    check_setuptools_version()
  File "/home/idap_user/Anaconda3/lib/python3.6/site-packages/pyscaffold/utils.py", line 289, in check_setuptools_version
    raise OldSetuptools
pyscaffold.exceptions.OldSetuptools: Your setuptools version is too old (<12). Use `pip install -U setuptools` to upgrade.
If you have the deprecated `distribute` package installed remove it or update to version 0.7.3._

I am already using setuptools-41.2.0. 

If I upgrade pyscaffold version, of course the installation error shows below:

_distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pyscaffold<3.1a0,>=3.0a0')_

**Comment by interpret-ml** [comment]
Hi @mohitsahay - thanks for the report!

We're finding it difficult to reproduce this PyScaffold/SALib error on our end. We're going to keep trying to see if we can get this error on our side. Will let you know when there's news.

**Comment by interpret-ml** [comment]
Hi @mohitsahay, 

We're unfortunately still unable to reproduce this. Is this still an issue for you on the recent releases of interpret?

Thanks!
